# Generated by Django 3.1.7 on 2021-03-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_assets', models.FloatField(max_length=255)),
                ('current_liabilities', models.FloatField(max_length=255)),
                ('working_capital', models.FloatField(max_length=255)),
                ('total_assets', models.FloatField(max_length=255)),
                ('net_income', models.FloatField(max_length=255)),
                ('return_on_equity', models.FloatField(max_length=255)),
                ('ebit', models.FloatField(max_length=255)),
                ('total_equity_shareholders', models.FloatField(max_length=255)),
                ('total_debt', models.FloatField(max_length=255)),
                ('interest_expenses', models.FloatField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
            ],
        ),
    ]
