# Generated by Django 3.1.7 on 2021-03-20 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('contact_number', models.IntegerField()),
                ('location', models.CharField(default='Sri Lanka', max_length=255)),
                ('business_type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField()),
                ('current_assets', models.FloatField(max_length=255)),
                ('current_liabilities', models.FloatField(max_length=255)),
                ('working_capital', models.FloatField(max_length=255)),
                ('total_assets', models.FloatField(max_length=255)),
                ('net_income', models.FloatField(max_length=255)),
                ('total_shareholders_equity', models.FloatField(max_length=255)),
                ('total_debt', models.FloatField(max_length=255)),
                ('long_term_debt', models.FloatField(max_length=255)),
                ('interest_expenses', models.FloatField(max_length=255)),
                ('cash_equivalents', models.FloatField(max_length=255)),
                ('total_liabilities', models.FloatField(max_length=255)),
                ('net_credit_sales', models.FloatField(max_length=255)),
                ('accounts_receivables', models.FloatField(max_length=255)),
                ('ebit', models.FloatField(max_length=255)),
                ('pd', models.FloatField(max_length=255)),
                ('credit_limit', models.FloatField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
            ],
        ),
    ]
