# Generated by Django 3.1.7 on 2021-04-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdetails',
            name='accounts_receivables',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='cash_equivalents',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='current_assets',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='current_liabilities',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='long_term_debt',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='net_credit_sales',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='net_income',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='total_debt',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='total_liabilities',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='total_shareholders_equity',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='working_capital',
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='cost_of_products_sold',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='depreciation',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='ebitda',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='extraordinary_items',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='gross_profit',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='net_profit',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='profit_on_operating_activities',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='profit_on_sales',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='sales',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='short_term_liabilities',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
