# Generated by Django 3.1.7 on 2021-03-05 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdetails',
            old_name='total_equity_shareholders',
            new_name='total_shareholders_equity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.CharField(default='Sri Lanka', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='current_ratio',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='debt_to_equity',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='financial_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
