# Generated by Django 3.1.7 on 2021-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210305_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='current_ratio',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='debt_to_equity',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='return_on_equity',
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='accounts_receivables',
            field=models.FloatField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='cash_equivalents',
            field=models.FloatField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='long_term_debt',
            field=models.FloatField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='net_credit_sales',
            field=models.FloatField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_liabilities',
            field=models.FloatField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
