# Generated by Django 3.1.7 on 2021-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210410_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdetails',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='net_profit',
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_expenses',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='total_liabilities',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
